version: 2

jobs:
  test-3.7: &test-template
    docker:
      - image: circleci/python:3.7
    branches:
      only:
        - master
        - dev
    steps:
      # Checkout repository
      - checkout
      # Install dependencies, uses cache if not update
      - restore_cache:
          key: test-deps-{{ .Branch }}-{{ checksum "requirements/test.txt" }}
      - run:
          name: install tests dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements/test.txt
            pip install -U pip setuptools
      - save_cache:
          key: test-deps-{{ .Branch }}-{{ checksum "requirements/test.txt" }}
          paths:
            - "venv"
      # Install tavolo
      - run:
          name: install tavolo
          command: |
            source venv/bin/activate
            python setup.py install
      # Run code tests
      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            pytest -s --cov=tavolo tests/
  test-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6
  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5
  test-3.4:
    <<: *test-template
    docker:
      - image: circleci/python:3.4
