version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.7:
          filters:
            branches:
              only:
                - master
                - dev
      - test-3.6:
          filters:
            branches:
              only:
                - master
                - dev
      - test-3.5:
          filters:
            branches:
              only:
                - master
                - dev
jobs:
  test-3.8: &test-template
    docker:
      - image: circleci/python:3.8
    steps:
      # Checkout repository
      - checkout
      # Install dependencies, uses cache if not updat
      - restore_cache:
          key: test-deps-{{ .Branch }}-{{ checksum "requirements/test.txt" }}
      - run:
          name: install tests dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -U pip
            pip install -r requirements/test.txt
            pip install -U pip setuptools
      - save_cache:
          key: test-deps-{{ .Branch }}-{{ checksum "requirements/test.txt" }}
          paths:
            - "venv"
      # Install tavolo
      - run:
          name: install tavolo
          command: |
            source venv/bin/activate
            python setup.py install
      # Run code tests
      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            pytest -s --cov=tavolo tests/
            codecov
  test-3.7:
    <<: *test-template
    docker:
      - image: circleci/python:3.7
  test-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6
